fix crash and error with texture atlas
- crashes at Project Export Settings > Preview Atlas
- error message when export project

```
ERROR: EditorImportExport::get_import_plugin_by_name: Condition ' !by_idx.has(p_string) ' is true. returned: Ref<EditorImportPlugin>()
   At: tools\editor\editor_import_export.cpp:1548
```

it is caused by https://github.com/godotengine/godot/commit/96ebea63e066ef27c623967f9c5004c0ca3a16ee#diff-67a74bd708380c6b3baa717bb178dd47R802