Fix warning using ERR_FAIL_INDEX on unsigned int
This method starting being used in 6e38d6ce58400f770ce18c4ea812da5aef6324a5,
which now triggers this warning from GCC 10:
```
./core/error_macros.h:151:25: error: comparison of unsigned expression in '< 0' is always false [-Werror=type-limits]
```